name: argon_user
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  dio:
  intl:
  cached_network_image:
  flutter_svg:
  ntp: ^2.0.0
  get_storage:
  table_sticky_headers:
  syncfusion_flutter_datepicker:
  month_year_picker:
  connectivity:
  kiwi:
  logging:
  shared_preferences:

  #  image_picker:
  flutter: 
    sdk: flutter

dev_dependencies:
  build_runner:
  flutter_lints: ^1.0.0
  json_serializable: ^6.1.5
  kiwi_generator:
  flutter_test:
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/


#flutter_native_splash:
#  color: "#ffffff"
#  image: "assets/logo.png"